### ISSUE TITLE
Dead body????

### ISSUE THREAD

**Issue by DHStyle541** [ImpulsiveLad/Arachnophilia#1]
Weird bug. testing solo no player only me but there is dead body???

![image](https://github.com/ImpulsiveLad/Arachnophilia/assets/154591650/91f21783-c108-4eaf-b619-5973bf2e7b68)

![image](https://github.com/ImpulsiveLad/Arachnophilia/assets/154591650/abfa029c-4444-48ea-9691-1cc96095fd6d)

Error Logs 
![image](https://github.com/ImpulsiveLad/Arachnophilia/assets/154591650/fdc33368-092e-4c41-bab8-8375dace2f9d)

**Comment by ImpulsiveLad** [comment]
That is a feature
